version: "3.2"
services:
    zipkin:
        image: openzipkin/zipkin:2
        ports:
          - 9411:9411
    rabbitmq3:
      image: rabbitmq:3-management
      ports:
          - 5672:5672
          - 15672:15672