server:
  port: 8072

spring:

  zipikin:
    base-url: http://zipikin-service:9411/

  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq-service
    port: 5672

  data:
    mongodb:
      host: mongo-service
      port: 27017
      database: catalogServiceDB


## Resilience4J configs for CircuitBreaker Pattern
resilience4j:
  circuitbreaker:
    instances:
      movie-service:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failueRateThreshold: 50
        waitDurationInOpenState: 50s
        permittedNumberOfCalssInHalfOpenState: 3
        automaticTransitionFromOpenToHalfIfOpenEnabled: true


  retry:
    instances:
      movie-service:
        maxAttempts: 3
        waitDuration: 10s

        retryExceptions:
          - feign.FeignException$InternalServerError
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException

management:
  endpoints:
    web:
      exposure:
        include: circuitbreakers,circuitbreakerevents,health,info,actuator
  info:
    env:
      enabled: true

  health:
    circuitbreakers:
      enabled: true

  endpoint:
    info:
      enabled: true
    health:
      show-details: always