server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: movie-service
          uri: lb://MOVIE-SERVICE
          predicates:
            - Path=/movie/**
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog/**
        - id: serie-service
          uri: lb://SERIES-SERVICE
          predicates:
            - Path=/series/**