server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 186124423952-bgn7qbrkts4crd46hsq5unhb70ai1uev.apps.googleusercontent.com
            client-secret: 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
            scope: openid
            redirect-uri: http://localhost:8080/login/oauth2/code/google
#   cloud:
#     gateway:
#       default-filters:
#         - TokenRelay
#       routes:
#         - id: movie-service
#           uri: lb://MOVIE-SERVICE
#           predicates:
#             - Path=/movie/**
#           filters:
#             - name: CircuitBreaker
#               args:
#                 name: movieServiceCircuitBreaker
#                 fallbackUri: forward:/fallback/movieServiceFallBack
#         - id: catalog-service
#           uri: lb://CATALOG-SERVICE
#           predicates:
#             - Path=/catalog/**
#           filters:
#             - name: CircuitBreaker
#               args:
#                 name: catalogServiceCircuitBreaker
#                 fallbackUri: forward:/fallback/catalogServiceFallBack
#         - id: series-service
#           uri: lb://SERIES-SERVICE
#           predicates:
#             - Path=/series/**
#           filters:
#             - name: CircuitBreaker
#               args:
#                 name: seriesServiceCircuitBreaker
#                 fallbackUri: forward:/fallback/seriesServiceFallBack

# # Resilience4J configs for CircuitBreaker Pattern
# resilience4j:
#   circuitbreaker:
#     instances:
#       movie-service:
#         allowHealthIndicatorToFail: false
#         registerHealthIndicator: true
#         slidingWindowType: COUNT_BASED
#         slidingWindowSize: 5
#         failueRateThreshold: 50
#         waitDurationInOpenState: 50s
#         permittedNumberOfCalssInHalfOpenState: 3
#         automaticTransitionFromOpenToHalfIfOpenEnabled: true
#       series-service:
#         allowHealthIndicatorToFail: false
#         registerHealthIndicator: true
#         slidingWindowType: COUNT_BASED
#         slidingWindowSize: 5
#         failueRateThreshold: 50
#         waitDurationInOpenState: 50s
#         permittedNumberOfCalssInHalfOpenState: 3
#         automaticTransitionFromOpenToHalfIfOpenEnabled: true
#       catalog-service:
#         allowHealthIndicatorToFail: false
#         registerHealthIndicator: true
#         slidingWindowType: COUNT_BASED
#         slidingWindowSize: 5
#         failueRateThreshold: 50
#         waitDurationInOpenState: 50s
#         permittedNumberOfCalssInHalfOpenState: 3
#         automaticTransitionFromOpenToHalfIfOpenEnabled: true


#   retry:
#     instances:
#       movie-service:
#         maxAttempts: 3
#         waitDuration: 10s

#         retryExceptions:
#           - feign.FeignException$InternalServerError
#           - org.springframework.web.client.HttpServerErrorException
#           - java.util.concurrent.TimeoutException
#           - java.io.IOException

#       series-service:
#         maxAttempts: 3
#         waitDuration: 10s

#         retryExceptions:
#           - feign.FeignException$InternalServerError
#           - org.springframework.web.client.HttpServerErrorException
#           - java.util.concurrent.TimeoutException
#           - java.io.IOException

#       catalog-service:
#         maxAttempts: 3
#         waitDuration: 10s

#         retryExceptions:
#           - feign.FeignException$InternalServerError
#           - org.springframework.web.client.HttpServerErrorException
#           - java.util.concurrent.TimeoutException
#           - java.io.IOException

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: circuitbreakers,circuitbreakerevents,health,info,actuator