server:
  port: 8082

spring:
#  datasource:
#    url: jdbc:mysql://localhost/movie-service?createDatabaseIfNotExist=true&serverTimezone=UTC-3&useSSl=false
#    username: perseidasdev # Alterar as credenciais para o ambiente local
#    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq-service
    port: 5672


## Resilience4J configs for CircuitBreaker Pattern
resilience4j:
  circuitbreaker:
    instances:
      movie-service:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failueRateThreshold: 50
        waitDurationInOpenState: 50s
        permittedNumberOfCalssInHalfOpenState: 3
        automaticTransitionFromOpenToHalfIfOpenEnabled: true


  retry:
    instances:
      movie-service:
        maxAttempts: 3
        waitDuration: 10s

        retryExceptions:
          - feign.FeignException$InternalServerError
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException

management:
  endpoints:
    web:
      exposure:
        include: circuitbreakers,circuitbreakerevents,health,info
  info:
    env:
      enabled: true

  health:
    circuitbreakers:
      enabled: true

  endpoint:
    info:
      enabled: true
    health:
      show-details: always