server:
  port: 8092
  servlet:
    context-path: /series/
  
spring:
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq-service
    port: 5672

info:
  name: Series service application!