server:
  port: 8092
  
spring:
  zipikin:
    base-url: http://zipikin-service:9411/

  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq-service
    port: 5672

  data:
    mongodb:
      host: mongo-service
      port: 27017
      database: serieServiceDB

info:
  name: Series service application!

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,actuator