server:
  port: 8761
spring:
  application:
    name: eureka-service
  zipkin:
    base-url: http://zipkin-service:9411/

eureka:
  instance:
    hostname: eureka-service
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

management:
  endpoints:
    web:
      exposure:
        include: health,info,actuator