spring:
  application:
    name: gateway

  zipkin:
    base-url: http://zipkin-service:9411/

  config:
    import: optional:configserver:http://config-service:8888

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Gateway Service Application
  svc:
    port: ${server.port}