spring:
  application:
    name: eureka-server

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

server:
  port: 8761
management:
  endpoints:
    web:
      exposure:
        include: health,info,actuator