server:
  port: 8888

spring:
  application:
    name: configserver

  cloud:
    config:
      server:
        git:
          uri: https://github.com/ronilsonalves/avaliacaoFinalBackend
          default-label: integradora-vi
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka